name: qiskit-metal
channels:
- conda-forge
- defaults
dependencies:
- python>=3.6
- pip
- addict
- descartes
- docutils
- geopandas
- ipython
- matplotlib
- numpy
- pandas
- pint
- pyepr-quantum
- pygments
- pyqode.python
- pyqt>=5.12
- qutip
- scipy
- shapely

- jupyter
- wheel


- pip:
  - gdspy>=1.5
