name: qiskit-metal
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pip
  - addict
  - cycler
  - descartes
  - docutils
  - gdspy>=1.5.2
  - geopandas
  - ipython
  - jedi>=0.16
  - matplotlib
  - numpy
  - pandas
  - pint
  - pyepr-quantum
  - pygments
  - pyqode.python
  - pyside2>=5.8
  - qutip
  - scipy
  - shapely

  - jupyter
  - wheel
